language: python
cache: pip
python: 
  - "2.7"

sudo: required

install:
  - pip install git+https://github.com/titom73/python-excel-serializer.git

script:
  - cd ci/
  - inetsix-excel-to-template -h
  - inetsix-excel-to-template -e ci/excel-demo.xlsx -s test -m table -n 3
